### ISSUE TITLE
I cannot build CADT from source

### ISSUE THREAD

**Issue by tommyJS** [MobileChromeApps/chrome-app-developer-tool#50]
Hi All,

I meet a strange error. I cannot build CADT from source. I am pasting the end of my output:

```
-compile:
    [javac] Compiling 99 source files to /home/tommyjs/Desktop/chrome-app-developer-tool/CADT/platforms/android/bin/classes
    [javac] /home/tommyjs/Desktop/chrome-app-developer-tool/CADT/platforms/android/src/org/chromium/ChromeSystemStorage.java:38: error: diamond operator is not supported in -source 1.5
    [javac]     private static List<EventInfo> pendingEvents = new ArrayList<>();
    [javac]                                                                  ^
    [javac]   (use -source 7 or higher to enable diamond operator)
    [javac] 1 error

BUILD FAILED
/home/tommyjs/android-sdk-linux/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/tommyjs/android-sdk-linux/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 9 seconds

/home/tommyjs/Desktop/chrome-app-developer-tool/CADT/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/home/tommyjs/Desktop/chrome-app-developer-tool/CADT/platforms/android/build.xml
Error: /home/tommyjs/Desktop/chrome-app-developer-tool/CADT/platforms/android/cordova/run: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

Previously, I could build custom CADT without any problem. Do you know what can be the root cause?

Thank you, in advance :)

**Comment by agrieve** [comment]
Lots of changes since you've tried this. Going to assume this is fixed, but please re-open if not.
